# Generated by Django 4.0.3 on 2022-07-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0002_orcamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faturamento_data', models.DateField()),
                ('faturamento_valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
