# Generated by Django 4.0.3 on 2022-11-18 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0003_faturamento_alter_orcamento_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('data_autorizacao', models.DateField(auto_now=True)),
                ('valor_autorizacao', models.DecimalField(decimal_places=2, max_digits=11)),
                ('autorizacao_aprovada', models.BooleanField()),
                ('justificativa', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamento.categoria')),
            ],
        ),
    ]
