# Generated by Django 4.0.3 on 2022-11-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0004_autorizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorizacao',
            name='autorizacao_aprovada',
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='autorizacao_status',
            field=models.CharField(choices=[('APR', 'APROVADO'), ('REP', 'REPROVADO'), ('AGU', 'AGUARDANDO')], default='AGU', max_length=20),
        ),
    ]
