# Generated by Django 4.0.3 on 2022-11-18 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orcamento', '0005_remove_autorizacao_autorizacao_aprovada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacao',
            name='despachante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despachante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='despacho',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to=settings.AUTH_USER_MODEL),
        ),
    ]
