# Generated by Django 4.0.3 on 2022-11-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0006_autorizacao_despachante_autorizacao_despacho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacao',
            name='autorizacao_status',
            field=models.CharField(choices=[('APR', 'Aprovado'), ('REP', 'Reprovado'), ('AGU', 'Aguardando')], default='AGU', max_length=20),
        ),
    ]
