# Generated by Django 4.0.3 on 2022-11-24 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0007_alter_autorizacao_autorizacao_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autorizacao',
            options={'permissions': [('change_task_status', 'Can change the status of tasks'), ('close_task', 'Can remove a task by setting its status as closed')]},
        ),
    ]
