# Generated by Django 4.0.3 on 2022-11-24 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0008_alter_autorizacao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autorizacao',
            options={'permissions': [('pode_despachar', 'Pode despachar autorizações')]},
        ),
    ]
