# Generated by Django 4.0.3 on 2023-01-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0009_alter_autorizacao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacao',
            name='descreve_utilizacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='utilizada',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
