# Generated by Django 4.0.3 on 2023-12-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0010_autorizacao_descreve_utilizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacao',
            name='autorizacao_status',
            field=models.CharField(choices=[('APR', 'Aprovado'), ('REP', 'Reprovado'), ('AGU', 'Aguardando')], default='AGU', max_length=3),
        ),
    ]
