# Generated by Django 4.0.3 on 2024-04-06 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ItemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aquisicao', models.DateField()),
                ('data_entrada', models.DateTimeField()),
                ('data_situacao', models.DateTimeField()),
                ('data_garantia', models.DateField()),
                ('numero_serie', models.CharField(max_length=30)),
                ('situacao', models.CharField(choices=[('EST', 'Estoque'), ('PRO', 'Producao'), ('MAN', 'Manutencao'), ('VEN', 'Vendido'), ('BAI', 'Baixado')], max_length=3)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.TextField()),
                ('principal', models.BooleanField(default=False)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sigla', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField()),
                ('quantidade_minima', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1)),
                ('imagem', models.ImageField(upload_to='produtos/%Y/%m/%d/')),
                ('observacao', models.TextField(blank=True)),
                ('cod_bar', models.CharField(blank=True, max_length=14, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.marca')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('data_despacho', models.DateTimeField(blank=True, null=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABE', 'Aberto'), ('AGU', 'Aguardando'), ('DEF', 'Deferido'), ('IND', 'Indeferido'), ('ENT', 'Entregue')], default='ABE', max_length=3)),
                ('recebido', models.BooleanField(default=False)),
                ('usuario_despacho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_despacho', to=settings.AUTH_USER_MODEL)),
                ('usuario_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_entrega', to=settings.AUTH_USER_MODEL)),
                ('usuario_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_pedido', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimento', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída'), ('T', 'Transferência'), ('A', 'Altera Status')], max_length=1)),
                ('responsavel', models.CharField(default='responsavel', max_length=50)),
                ('item_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.itemproduto')),
                ('local_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='almox.localizacao')),
                ('local_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origem', to='almox.localizacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='itemproduto',
            name='localizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.localizacao'),
        ),
        migrations.AddField(
            model_name='itemproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.produto'),
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregue', models.BooleanField(default=False)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.produto')),
            ],
        ),
    ]
