# Generated by Django 4.0.3 on 2024-04-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'permissions': [('despachar', 'Pode despachar pedido')]},
        ),
    ]
