# Generated by Django 4.0.3 on 2024-04-07 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almox', '0002_alter_pedido_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'permissions': [('despachar', 'Pode despachar pedido'), ('entregar', 'Pode entregar pedido')]},
        ),
    ]
