# Generated by Django 4.0.3 on 2023-01-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_contato_agendamento_alter_contato_concluido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_agendamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
