# Generated by Django 4.0.3 on 2023-01-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_remove_contato_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='sucesso',
        ),
        migrations.AddField(
            model_name='contato',
            name='resultado',
            field=models.CharField(blank=True, choices=[('SIM', 'Produto Vendido'), ('NAO', 'Venda Não Realizada')], max_length=3),
        ),
    ]
