# Generated by Django 4.0.3 on 2023-01-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_remove_contato_sucesso_contato_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
