# Generated by Django 4.0.3 on 2022-12-17 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_nome', models.CharField(max_length=50)),
                ('pontos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_refencia', models.IntegerField()),
                ('pontos', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_nome', models.CharField(max_length=50)),
                ('pontos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('realizado', models.DecimalField(decimal_places=2, max_digits=6)),
                ('orcado', models.DecimalField(decimal_places=2, max_digits=6)),
                ('meta_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.area')),
            ],
        ),
        migrations.CreateModel(
            name='GameMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.IntegerField()),
                ('objetivo', models.DecimalField(decimal_places=0, max_digits=4)),
                ('pontos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('game_ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='game_mes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamemensal'),
        ),
    ]
