# Generated by Django 4.0.3 on 2022-12-20 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='data_atualizacao',
            field=models.DateField(blank=True, default=datetime.datetime(2000, 1, 10, 0, 0)),
        ),
        migrations.AddField(
            model_name='meta',
            name='pontos_anterior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
