# Generated by Django 4.0.3 on 2023-01-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_pontos_anterior_meta_realizado_anterior'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meta',
            options={'permissions': [('Atualiza_metas', 'Pode atualizar metas')]},
        ),
    ]
