# Generated by Django 4.0.3 on 2023-01-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_meta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ano_refencia',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='gamemensal',
            name='mes_referencia',
            field=models.CharField(max_length=20),
        ),
    ]
